apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app.kubernetes.io/name: tracee
    app.kubernetes.io/component: tracee
    app.kubernetes.io/part-of: tracee
  name: tracee
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: tracee
  template:
    metadata:
      labels:
        app.kubernetes.io/name: tracee
      name: tracee
    spec:
      containers:
      - image: aquasec/tracee:latest
        imagePullPolicy: Always
        command: ["./tracee-ebpf"]
        args: ["--trace","comm=bash", "--trace","follow","--output","out-file:/tmp/tracee/tracee-logs.gob"]
        # args: ["--trace","comm=bash","--trace","follow","output","out-file",":/home/tracee-logs/tracee.log" ]
        # args:
          # - --webhook http://postee-svc:8080 --webhook-template ./templates/rawjson.tmpl --webhook-content-type application/json
        name: tracee
        securityContext:
          privileged: true
        volumeMounts:
        - name: tmp-tracee
          mountPath: /tmp/tracee
        - name: usr-src
          mountPath: /usr/src
          readOnly: true  
        - name: lib-modules
          mountPath: /lib/modules/
          readOnly: true
        resources:
          limits:
            cpu: 500m
            memory: 300Mi
          requests:
            cpu: 350m
            memory: 50Mi
      tolerations:
        - effect: NoSchedule
          operator: Exists
        - effect: NoExecute
          operator: Exists
      volumes:
      - hostPath:
          path: /home/tracee-logs
        name: tmp-tracee
      - hostPath:
          path: /usr/src
        name: usr-src
      - hostPath:
          path: /lib/modules
        name: lib-modules

